### ISSUE TITLE
SDK 4.0: Data not persisting 

### ISSUE THREAD

**Issue by BlackLamb** [gregoiresage/enamel#9]
When I compile under 3.14 my data properly persits. But once I upgraded to the new 4.0 Pebble SDK everything is set to the default values, every time I run the app. I put some logging into the generated enamel.c and "if(persist_exists(ENAMEL_PKEY) && persist_exists(ENAMEL_DICT_PKEY))" in the init function never evaluates true.

**Comment by gregoiresage** [comment]
Weird... I don't reproduce the problem on my apps.
Do you call enamel_deinit at the end ?

Could you check if the return of prv_save_generic_data equals s_dict_size
in the enamel_deinit function ?

2016-08-31 6:54 GMT+02:00 BlackLamb notifications@github.com:

**Comment by BlackLamb** [comment]
Found it my app was crashing with a double free before deinit was called, sorry for the false alarm.
